spring:
  application:
    name: backend
  ai:
    openai:
      api-key: ${GMS_API_KEY}
      base-url: https://gms.ssafy.io/gmsapi/api.openai.com

  datasource:
    url: jdbc:mysql://localhost:3306/wtd_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    # 디버깅 위해 추가
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: wtd-secret-key-for-jwt-authentication-very-important
  access-token-expiration: 1800000 # 30분
  refresh-token-expiration: 1209600000 # 14일

gms:
  base-url: https://gms.ssafy.io/gmsapi/api.openai.com/v1/chat/completions # o3-mini 모델
  api-key: ${GMS_API_KEY}

clova:
  ocr:
    invoke:
      url: ${INVOKE_URL}
    secret:
      key: ${CLOVA_KEY}

ev:
  charger:
    key: ${EV_CHARGER_KEY}

weather:
  api:
    key: ${WEATHER_API_KEY}