spring:
  application:
    name: backend
  ai:
    openai:
      api-key: ${GMS_API_KEY}
      base-url: https://gms.ssafy.io/gmsapi/api.openai.com
      chat:
        options:
          model: o3-mini
          temperature: 1.0

  datasource:
    url: jdbc:mysql://70.12.103.177:3306/wtd_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    # 디버깅 위해 추가
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: wtd-secret-key-for-jwt-authentication-very-important
  access-token-expiration: 1800000 # 30분
  refresh-token-expiration: 1209600000 # 14일

clova:
  ocr:
    invoke:
      url: ${INVOKE_URL}
    secret:
      key: ${CLOVA_KEY}

ev:
  charger:
    key: ${EV_CHARGER_KEY}

weather:
  api:
    key: ${WEATHER_API_KEY}

kakao:
  rest-api:
    key: ${KAKAO_REST_KEY}