spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/wtd_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: wtd-secret-key-for-jwt-authentication-very-important
  access-token-expiration: 1800000 # 30분
  refresh-token-expiration: 1209600000 # 14일